### ISSUE TITLE
README.md example does not work.

### ISSUE THREAD

**Issue by dmtucker** [sarenji/pyrc#23]
I did exactly as the example shows, and here are the results I got.
Machine Specs: Ubuntu 14.04.1, Python 2.7.6

[18:06] --> dmtucker (~dmtucker@host.domain.tld) has joined this channel.
[18:06] --> HiBot (~hibot@host.domain.tld) has joined this channel.
[18:06] <dmtucker> HiBot, sayhi
[18:06] <-- HiBot (~hibot@host.domain.tld) has left this server (Remote host closed the connection).

$ python test.py
...
Traceback (most recent call last):
  File "test.py", line 27, in <module>
    bot.connect()
  File "/usr/local/lib/python2.7/dist-packages/pyrc/bots.py", line 44, in connect
    self.listen()
  File "/usr/local/lib/python2.7/dist-packages/pyrc/bots.py", line 68, in listen
    self.parseline(line)
  File "/usr/local/lib/python2.7/dist-packages/pyrc/bots.py", line 79, in parseline
    self.receivemessage(channel, nick, message)
  File "/usr/local/lib/python2.7/dist-packages/pyrc/bots.py", line 109, in receivemessage
    self.parsecommand(channel, message)
  File "/usr/local/lib/python2.7/dist-packages/pyrc/bots.py", line 131, in parsecommand
    command_func(self, channel, _match.groups(), *_match.groupdict())
  File "/usr/local/lib/python2.7/dist-packages/pyrc/utils/hooks.py", line 19, in wrapped_command
    return func(_args, *_kwargs)
TypeError: sayhi() takes exactly 3 arguments (2 given)

**Comment by dmtucker** [comment]
example.py doesn't work either or run at all.

**Comment by dmtucker** [comment]
These issues do not seem to present if the repo is cloned instead of installed with pip!

**Comment by wei2912** [comment]
It looks like the version on pip may be outdated. @sarenji Would it be possible to fix this? :)

Meanwhile, you should use the cloned version. It comes with a couple of new features.

**Comment by sarenji** [comment]
Sorry for the delay. I've uploaded `v0.6.6` to PyPI - can you try again?

**Comment by dmtucker** [comment]
WFM with Python 2
